# Generated by Django 4.2.5 on 2023-09-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='view',
            field=models.ManyToManyField(through='app.LessonView', to='app.userprofile'),
        ),
    ]
